export const EXPERIENCE_LEVELS = [
    "Fresher",
    "Internship",
    "Associate",
    "Senior",
    "Lead",
    "Executive"
];

export const SEARCH_PLATFORMS = [
    "All",
    "LinkedIn",
    "Glassdoor",
    "Indeed",
    "Naukri",
    "Google"
];

export const COMPANY_SIZES = [
    "Startup",
    "Small",
    "Mid-size",
    "Large",
    "MNC"
];

export const POPULAR_JOB_TITLES = [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Product Manager",
    "UI/UX Designer",
    "DevOps Engineer",
    "Cloud Architect",
    "Mobile App Developer",
    "QA Engineer",
    "System Administrator",
    "Business Analyst",
    "Marketing Manager",
    "Sales Representative",
    "HR Manager",
    "Content Writer",
    "Graphic Designer",
    "Project Manager",
    "Accountant",
    "Teacher",
    "Nurse",
    "Customer Support",
    "Medical Billing",
    "Medical Coder",
    "Healthcare Administrator",
    "Pharmacy Technician",
    "Physician Assistant",
    "Physical Therapist",
    "Occupational Therapist",
    "Radiologic Technologist",
    "Clinical Laboratory Technician",
    "Dental Hygienist"
];

export const POPULAR_LOCATIONS = [
    // Remote
    "Remote",
    "Work from Home",
    "Hybrid",

    // Major Tech Hubs (India)
    "Bangalore, Karnataka",
    "Hyderabad, Telangana",
    "Pune, Maharashtra",
    "Chennai, Tamil Nadu",
    "Gurgaon, Haryana",
    "Noida, Uttar Pradesh",
    "Mumbai, Maharashtra",
    "Delhi NCR",
    "Kolkata, West Bengal",
    "Ahmedabad, Gujarat",

    // States & UTs (India)
    "Andhra Pradesh, India",
    "Arunachal Pradesh, India",
    "Assam, India",
    "Bihar, India",
    "Chhattisgarh, India",
    "Goa, India",
    "Gujarat, India",
    "Haryana, India",
    "Himachal Pradesh, India",
    "Jharkhand, India",
    "Karnataka, India",
    "Kerala, India",
    "Madhya Pradesh, India",
    "Maharashtra, India",
    "Manipur, India",
    "Meghalaya, India",
    "Mizoram, India",
    "Nagaland, India",
    "Odisha, India",
    "Punjab, India",
    "Rajasthan, India",
    "Sikkim, India",
    "Tamil Nadu, India",
    "Telangana, India",
    "Tripura, India",
    "Uttar Pradesh, India",
    "Uttarakhand, India",
    "West Bengal, India",
    "Andaman and Nicobar Islands, India",
    "Chandigarh, India",
    "Dadra and Nagar Haveli and Daman and Diu, India",
    "Lakshadweep, India",
    "Delhi, India",
    "Puducherry, India",
    "Ladakh, India",
    "Jammu and Kashmir, India",

    // Districts - Tamil Nadu
    "Ariyalur, Tamil Nadu",
    "Chengalpattu, Tamil Nadu",
    "Coimbatore, Tamil Nadu",
    "Cuddalore, Tamil Nadu",
    "Dharmapuri, Tamil Nadu",
    "Dindigul, Tamil Nadu",
    "Erode, Tamil Nadu",
    "Kallakurichi, Tamil Nadu",
    "Kanchipuram, Tamil Nadu",
    "Kanyakumari, Tamil Nadu",
    "Karur, Tamil Nadu",
    "Krishnagiri, Tamil Nadu",
    "Madurai, Tamil Nadu",
    "Nagapattinam, Tamil Nadu",
    "Namakkal, Tamil Nadu",
    "Nilgiris, Tamil Nadu",
    "Perambalur, Tamil Nadu",
    "Pudukkottai, Tamil Nadu",
    "Ramanathapuram, Tamil Nadu",
    "Ranipet, Tamil Nadu",
    "Salem, Tamil Nadu",
    "Sivaganga, Tamil Nadu",
    "Tenkasi, Tamil Nadu",
    "Thanjavur, Tamil Nadu",
    "Theni, Tamil Nadu",
    "Thoothukudi, Tamil Nadu",
    "Tiruchirappalli, Tamil Nadu",
    "Tirunelveli, Tamil Nadu",
    "Tirupathur, Tamil Nadu",
    "Tiruppur, Tamil Nadu",
    "Tiruvallur, Tamil Nadu",
    "Tiruvannamalai, Tamil Nadu",
    "Tiruvarur, Tamil Nadu",
    "Vellore, Tamil Nadu",
    "Viluppuram, Tamil Nadu",
    "Virudhunagar, Tamil Nadu",

    // Districts - Kerala
    "Alappuzha, Kerala",
    "Ernakulam, Kerala",
    "Idukki, Kerala",
    "Kannur, Kerala",
    "Kasaragod, Kerala",
    "Kollam, Kerala",
    "Kottayam, Kerala",
    "Kozhikode, Kerala",
    "Malappuram, Kerala",
    "Palakkad, Kerala",
    "Pathanamthitta, Kerala",
    "Thiruvananthapuram, Kerala",
    "Thrissur, Kerala",
    "Wayanad, Kerala",

    // Districts - Karnataka
    "Bagalkot, Karnataka",
    "Ballari, Karnataka",
    "Belagavi, Karnataka",
    "Bengaluru Rural, Karnataka",
    "Bengaluru Urban, Karnataka",
    "Bidar, Karnataka",
    "Chamarajanagar, Karnataka",
    "Chikkaballapura, Karnataka",
    "Chikkamagaluru, Karnataka",
    "Chitradurga, Karnataka",
    "Dakshina Kannada, Karnataka",
    "Davangere, Karnataka",
    "Dharwad, Karnataka",
    "Gadag, Karnataka",
    "Hassan, Karnataka",
    "Haveri, Karnataka",
    "Kalaburagi, Karnataka",
    "Kodagu, Karnataka",
    "Kolar, Karnataka",
    "Koppal, Karnataka",
    "Mandya, Karnataka",
    "Mysuru, Karnataka",
    "Raichur, Karnataka",
    "Ramanagara, Karnataka",
    "Shivamogga, Karnataka",
    "Tumakuru, Karnataka",
    "Udupi, Karnataka",
    "Uttara Kannada, Karnataka",
    "Vijayapura, Karnataka",
    "Yadgir, Karnataka",

    // Districts - Maharashtra
    "Ahmednagar, Maharashtra",
    "Akola, Maharashtra",
    "Amravati, Maharashtra",
    "Aurangabad, Maharashtra",
    "Beed, Maharashtra",
    "Bhandara, Maharashtra",
    "Buldhana, Maharashtra",
    "Chandrapur, Maharashtra",
    "Dhule, Maharashtra",
    "Gadchiroli, Maharashtra",
    "Gondia, Maharashtra",
    "Hingoli, Maharashtra",
    "Jalgaon, Maharashtra",
    "Jalna, Maharashtra",
    "Kolhapur, Maharashtra",
    "Latur, Maharashtra",
    "Mumbai City, Maharashtra",
    "Mumbai Suburban, Maharashtra",
    "Nagpur, Maharashtra",
    "Nanded, Maharashtra",
    "Nandurbar, Maharashtra",
    "Nashik, Maharashtra",
    "Osmanabad, Maharashtra",
    "Palghar, Maharashtra",
    "Parbhani, Maharashtra",
    "Raigad, Maharashtra",
    "Ratnagiri, Maharashtra",
    "Sangli, Maharashtra",
    "Satara, Maharashtra",
    "Sindhudurg, Maharashtra",
    "Solapur, Maharashtra",
    "Thane, Maharashtra",
    "Wardha, Maharashtra",
    "Washim, Maharashtra",
    "Yavatmal, Maharashtra",

    // Other Major Cities (India)
    "Visakhapatnam, Andhra Pradesh",
    "Vijayawada, Andhra Pradesh",
    "Guwahati, Assam",
    "Patna, Bihar",
    "Raipur, Chhattisgarh",
    "Panaji, Goa",
    "Surat, Gujarat",
    "Vadodara, Gujarat",
    "Rajkot, Gujarat",
    "Shimla, Himachal Pradesh",
    "Ranchi, Jharkhand",
    "Jamshedpur, Jharkhand",
    "Bhopal, Madhya Pradesh",
    "Indore, Madhya Pradesh",
    "Gwalior, Madhya Pradesh",
    "Bhubaneswar, Odisha",
    "Cuttack, Odisha",
    "Ludhiana, Punjab",
    "Amritsar, Punjab",
    "Jaipur, Rajasthan",
    "Udaipur, Rajasthan",
    "Jodhpur, Rajasthan",
    "Gangtok, Sikkim",
    "Warangal, Telangana",
    "Agartala, Tripura",
    "Lucknow, Uttar Pradesh",
    "Kanpur, Uttar Pradesh",
    "Varanasi, Uttar Pradesh",
    "Agra, Uttar Pradesh",
    "Dehradun, Uttarakhand",
    "Haridwar, Uttarakhand",

    // International
    "United States",
    "United Kingdom",
    "Canada",
    "Germany",
    "Australia",
    "Singapore",
    "UAE",
    "Silicon Valley",
    "London, UK",
    "New York, NY",
    "Dubai, UAE"
];

export const POPULAR_SKILLS = [
    "React",
    "Node.js",
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "TypeScript",
    "HTML/CSS",
    "SQL",
    "NoSQL",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "Git",
    "CI/CD",
    "Agile",
    "Scrum",
    "Machine Learning",
    "Deep Learning",
    "Data Analysis",
    "Project Management",
    "Communication",
    "Leadership",
    "Problem Solving",
    "Teamwork",
    "Time Management",
    "Critical Thinking",
    "Creativity",
    "Adaptability",
    "Work Ethic",
    "Attention to Detail",
    "Interpersonal Skills",
    "Emotional Intelligence",
    "Negotiation",
    "Conflict Resolution",
    "Decision Making",
    "Stress Management",
    "Public Speaking",
    "Writing",
    "Research",
    "Analytical Skills",
    "Technical Skills",
    "Soft Skills",
    "Hard Skills",
    "Transferable Skills",
    "Job-Specific Skills",
    "Industry-Specific Skills",
    "Domain Knowledge",
    "Business Acumen",
    "Financial Literacy",
    "Marketing",
    "Sales",
    "Customer Service",
    "Human Resources",
    "Operations",
    "Strategy",
    "Management",
    "Entrepreneurship",
    "Innovation",
    "Design Thinking",
    "User Experience (UX)",
    "User Interface (UI)",
    "Graphic Design",
    "Web Design",
    "Mobile App Development",
    "Software Development",
    "Database Management",
    "Network Security",
    "Cybersecurity",
    "Cloud Computing",
    "Artificial Intelligence (AI)",
    "Internet of Things (IoT)",
    "Blockchain",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
    "Robotics",
    "Automation",
    "Big Data",
    "Data Science",
    "Business Intelligence (BI)",
    "Analytics",
    "Statistics",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Engineering",
    "Architecture",
    "Medicine",
    "Law",
    "Education",
    "Finance",
    "Accounting",
    "Economics",
    "Psychology",
    "Sociology",
    "Philosophy",
    "History",
    "Literature",
    "Languages",
    "Arts",
    "Music",
    "Sports",
    "Gaming",
    "Travel",
    "Food",
    "Fashion",
    "Beauty",
    "Health",
    "Fitness",
    "Wellness",
    "Lifestyle",
    "Culture",
    "Politics",
    "Religion",
    "Spirituality",
    "Environment",
    "Sustainability",
    "Social Impact",
    "Volunteering",
    "Philanthropy",
    "Community Service",
    "Mentorship",
    "Networking",
    "Personal Branding",
    "Career Development",
    "Professional Development",
    "Lifelong Learning",
    "Growth Mindset",
    "Resilience",
    "Perseverance",
    "Grit",
    "Passion",
    "Purpose",
    "Values",
    "Ethics",
    "Integrity",
    "Trust",
    "Respect",
    "Empathy",
    "Compassion",
    "Kindness",
    "Gratitude",
    "Happiness",
    "Success",
    "Fulfillment",
    "Balance",
    "Well-being",
    "Mental Health",
    "Physical Health",
    "Emotional Health",
    "Spiritual Health",
    "Financial Health",
    "Social Health",
    "Environmental Health",
    "Occupational Health",
    "Intellectual Health",
    "Holistic Health",
    "Integrative Health",
    "Alternative Medicine",
    "Complementary Medicine",
    "Traditional Medicine",
    "Modern Medicine",
    "Healthcare",
    "Public Health",
    "Global Health",
    "One Health",
    "Planetary Health",
    "Universal Health Coverage",
    "Health Equity",
    "Social Determinants of Health",
    "Health Disparities",
    "Health Justice",
    "Health Policy",
    "Health Economics",
    "Health Systems",
    "Health Informatics",
    "Health Technology",
    "Digital Health",
    "Telehealth",
    "mHealth",
    "eHealth",
    "Health Innovation",
    "Health Entrepreneurship",
    "Health Leadership",
    "Health Management",
    "Health Administration",
    "Health Education",
    "Health Promotion",
    "Health Communication",
    "Health Advocacy",
    "Health Activism",
    "Health Research",
    "Health Science",
    "Health Professions",
    "Health Careers",
    "Health Jobs",
    "Health Workforce",
    "Health Human Resources",
    "Health Labor Market",
    "Health Economics",
    "Health Finance",
    "Health Insurance",
    "Health Coverage",
    "Health Access",
    "Health Quality",
    "Health Safety",
    "Health Outcomes",
    "Health Impact",
    "Health Value",
    "Health Cost",
    "Health Expenditure",
    "Health Spending",
    "Health Budget",
    "Health Funding",
    "Health Financing",
    "Health Investment",
    "Health Resources",
    "Health Infrastructure",
    "Health Facilities",
    "Health Services",
    "Health Care",
    "Medical Care",
    "Clinical Care",
    "Patient Care",
    "Nursing Care",
    "Social Care",
    "Community Care",
    "Home Care",
    "Long-term Care",
    "Palliative Care",
    "Hospice Care",
    "End-of-life Care",
    "Primary Care",
    "Secondary Care",
    "Tertiary Care",
    "Quaternary Care",
    "Acute Care",
    "Chronic Care",
    "Preventive Care",
    "Curative Care",
    "Rehabilitative Care",
    "Restorative Care",
    "Maintenance Care",
    "Supportive Care",
    "Holistic Care",
    "Integrative Care",
    "Collaborative Care",
    "Coordinated Care",
    "Managed Care",
    "Accountable Care",
    "Value-based Care",
    "Patient-centered Care",
    "Person-centered Care",
    "Family-centered Care",
    "Community-centered Care",
    "Population-centered Care",
    "Evidence-based Care",
    "Quality Care",
    "Safe Care",
    "Effective Care",
    "Efficient Care",
    "Equitable Care",
    "Timely Care",
    "Accessible Care",
    "Affordable Care",
    "Sustainable Care",
    "Resilient Care",
    "Innovative Care",
    "Transformative Care",
    "Future Care"
];
